name: C/C++ CI
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-20.04]
        compiler:
          - gcc
          - clang
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make
